// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleMode int32

const (
	ScheduleMode_FIFO            ScheduleMode = 0
	ScheduleMode_STRICT_PRIORITY ScheduleMode = 1
	ScheduleMode_DQN_ADAPTIVE    ScheduleMode = 2
)

// Enum value maps for ScheduleMode.
var (
	ScheduleMode_name = map[int32]string{
		0: "FIFO",
		1: "STRICT_PRIORITY",
		2: "DQN_ADAPTIVE",
	}
	ScheduleMode_value = map[string]int32{
		"FIFO":            0,
		"STRICT_PRIORITY": 1,
		"DQN_ADAPTIVE":    2,
	}
)

func (x ScheduleMode) Enum() *ScheduleMode {
	p := new(ScheduleMode)
	*p = x
	return p
}

func (x ScheduleMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleMode) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (ScheduleMode) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x ScheduleMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleMode.Descriptor instead.
func (ScheduleMode) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

type MessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Priority      uint32                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEnvelope) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MessageEnvelope) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MessageEnvelope) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageEnvelope) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MessageEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TopicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NumPartitions int32                  `protobuf:"varint,2,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	Mode          ScheduleMode           `protobuf:"varint,3,opt,name=mode,proto3,enum=nyaqueue.ScheduleMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicInfo) Reset() {
	*x = TopicInfo{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInfo) ProtoMessage() {}

func (x *TopicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInfo.ProtoReflect.Descriptor instead.
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *TopicInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicInfo) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *TopicInfo) GetMode() ScheduleMode {
	if x != nil {
		return x.Mode
	}
	return ScheduleMode_FIFO
}

type TopicScheduleConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              ScheduleMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=nyaqueue.ScheduleMode" json:"mode,omitempty"`
	PriorityLevels    int32                  `protobuf:"varint,2,opt,name=priority_levels,json=priorityLevels,proto3" json:"priority_levels,omitempty"`
	AntiStarvationMs  int64                  `protobuf:"varint,3,opt,name=anti_starvation_ms,json=antiStarvationMs,proto3" json:"anti_starvation_ms,omitempty"`
	DqnThrottleOnLoad float64                `protobuf:"fixed64,4,opt,name=dqn_throttle_on_load,json=dqnThrottleOnLoad,proto3" json:"dqn_throttle_on_load,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TopicScheduleConfig) Reset() {
	*x = TopicScheduleConfig{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicScheduleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicScheduleConfig) ProtoMessage() {}

func (x *TopicScheduleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicScheduleConfig.ProtoReflect.Descriptor instead.
func (*TopicScheduleConfig) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *TopicScheduleConfig) GetMode() ScheduleMode {
	if x != nil {
		return x.Mode
	}
	return ScheduleMode_FIFO
}

func (x *TopicScheduleConfig) GetPriorityLevels() int32 {
	if x != nil {
		return x.PriorityLevels
	}
	return 0
}

func (x *TopicScheduleConfig) GetAntiStarvationMs() int64 {
	if x != nil {
		return x.AntiStarvationMs
	}
	return 0
}

func (x *TopicScheduleConfig) GetDqnThrottleOnLoad() float64 {
	if x != nil {
		return x.DqnThrottleOnLoad
	}
	return 0
}

// ProduceMessage is a single message inside a batch ProduceRequest.
type ProduceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Priority      uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceMessage) Reset() {
	*x = ProduceMessage{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceMessage) ProtoMessage() {}

func (x *ProduceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceMessage.ProtoReflect.Descriptor instead.
func (*ProduceMessage) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *ProduceMessage) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProduceMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProduceMessage) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ProduceResult is a per-message result inside a batch ProduceResponse.
type ProduceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResult) Reset() {
	*x = ProduceResult{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResult) ProtoMessage() {}

func (x *ProduceResult) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResult.ProtoReflect.Descriptor instead.
func (*ProduceResult) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *ProduceResult) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceResult) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\bnyaqueue\"\x8b\x01\n" +
	"\x0fMessageEnvelope\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"t\n" +
	"\tTopicInfo\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0enum_partitions\x18\x02 \x01(\x05R\rnumPartitions\x12*\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x16.nyaqueue.ScheduleModeR\x04mode\"\xc9\x01\n" +
	"\x13TopicScheduleConfig\x12*\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x16.nyaqueue.ScheduleModeR\x04mode\x12'\n" +
	"\x0fpriority_levels\x18\x02 \x01(\x05R\x0epriorityLevels\x12,\n" +
	"\x12anti_starvation_ms\x18\x03 \x01(\x03R\x10antiStarvationMs\x12/\n" +
	"\x14dqn_throttle_on_load\x18\x04 \x01(\x01R\x11dqnThrottleOnLoad\"T\n" +
	"\x0eProduceMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\"E\n" +
	"\rProduceResult\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset*?\n" +
	"\fScheduleMode\x12\b\n" +
	"\x04FIFO\x10\x00\x12\x13\n" +
	"\x0fSTRICT_PRIORITY\x10\x01\x12\x10\n" +
	"\fDQN_ADAPTIVE\x10\x02B(Z&github.com/Nyamerka/NyaQueue/pkg/protob\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_proto_goTypes = []any{
	(ScheduleMode)(0),           // 0: nyaqueue.ScheduleMode
	(*MessageEnvelope)(nil),     // 1: nyaqueue.MessageEnvelope
	(*TopicInfo)(nil),           // 2: nyaqueue.TopicInfo
	(*TopicScheduleConfig)(nil), // 3: nyaqueue.TopicScheduleConfig
	(*ProduceMessage)(nil),      // 4: nyaqueue.ProduceMessage
	(*ProduceResult)(nil),       // 5: nyaqueue.ProduceResult
}
var file_model_proto_depIdxs = []int32{
	0, // 0: nyaqueue.TopicInfo.mode:type_name -> nyaqueue.ScheduleMode
	0, // 1: nyaqueue.TopicScheduleConfig.mode:type_name -> nyaqueue.ScheduleMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
