// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: queue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_queue_proto protoreflect.FileDescriptor

const file_queue_proto_rawDesc = "" +
	"\n" +
	"\vqueue.proto\x12\bnyaqueue\x1a\rrequest.proto\x1a\x0eresponse.proto2\xeb\x03\n" +
	"\bNyaQueue\x12>\n" +
	"\aProduce\x12\x18.nyaqueue.ProduceRequest\x1a\x19.nyaqueue.ProduceResponse\x12>\n" +
	"\aConsume\x12\x18.nyaqueue.ConsumeRequest\x1a\x19.nyaqueue.ConsumeResponse\x12;\n" +
	"\x06Commit\x12\x17.nyaqueue.CommitRequest\x1a\x18.nyaqueue.CommitResponse\x12J\n" +
	"\vCreateTopic\x12\x1c.nyaqueue.CreateTopicRequest\x1a\x1d.nyaqueue.CreateTopicResponse\x12J\n" +
	"\vDeleteTopic\x12\x1c.nyaqueue.DeleteTopicRequest\x1a\x1d.nyaqueue.DeleteTopicResponse\x12G\n" +
	"\n" +
	"ListTopics\x12\x1b.nyaqueue.ListTopicsRequest\x1a\x1c.nyaqueue.ListTopicsResponse\x12A\n" +
	"\n" +
	"GetMetrics\x12\x18.nyaqueue.MetricsRequest\x1a\x19.nyaqueue.MetricsResponseB(Z&github.com/Nyamerka/NyaQueue/pkg/protob\x06proto3"

var file_queue_proto_goTypes = []any{
	(*ProduceRequest)(nil),      // 0: nyaqueue.ProduceRequest
	(*ConsumeRequest)(nil),      // 1: nyaqueue.ConsumeRequest
	(*CommitRequest)(nil),       // 2: nyaqueue.CommitRequest
	(*CreateTopicRequest)(nil),  // 3: nyaqueue.CreateTopicRequest
	(*DeleteTopicRequest)(nil),  // 4: nyaqueue.DeleteTopicRequest
	(*ListTopicsRequest)(nil),   // 5: nyaqueue.ListTopicsRequest
	(*MetricsRequest)(nil),      // 6: nyaqueue.MetricsRequest
	(*ProduceResponse)(nil),     // 7: nyaqueue.ProduceResponse
	(*ConsumeResponse)(nil),     // 8: nyaqueue.ConsumeResponse
	(*CommitResponse)(nil),      // 9: nyaqueue.CommitResponse
	(*CreateTopicResponse)(nil), // 10: nyaqueue.CreateTopicResponse
	(*DeleteTopicResponse)(nil), // 11: nyaqueue.DeleteTopicResponse
	(*ListTopicsResponse)(nil),  // 12: nyaqueue.ListTopicsResponse
	(*MetricsResponse)(nil),     // 13: nyaqueue.MetricsResponse
}
var file_queue_proto_depIdxs = []int32{
	0,  // 0: nyaqueue.NyaQueue.Produce:input_type -> nyaqueue.ProduceRequest
	1,  // 1: nyaqueue.NyaQueue.Consume:input_type -> nyaqueue.ConsumeRequest
	2,  // 2: nyaqueue.NyaQueue.Commit:input_type -> nyaqueue.CommitRequest
	3,  // 3: nyaqueue.NyaQueue.CreateTopic:input_type -> nyaqueue.CreateTopicRequest
	4,  // 4: nyaqueue.NyaQueue.DeleteTopic:input_type -> nyaqueue.DeleteTopicRequest
	5,  // 5: nyaqueue.NyaQueue.ListTopics:input_type -> nyaqueue.ListTopicsRequest
	6,  // 6: nyaqueue.NyaQueue.GetMetrics:input_type -> nyaqueue.MetricsRequest
	7,  // 7: nyaqueue.NyaQueue.Produce:output_type -> nyaqueue.ProduceResponse
	8,  // 8: nyaqueue.NyaQueue.Consume:output_type -> nyaqueue.ConsumeResponse
	9,  // 9: nyaqueue.NyaQueue.Commit:output_type -> nyaqueue.CommitResponse
	10, // 10: nyaqueue.NyaQueue.CreateTopic:output_type -> nyaqueue.CreateTopicResponse
	11, // 11: nyaqueue.NyaQueue.DeleteTopic:output_type -> nyaqueue.DeleteTopicResponse
	12, // 12: nyaqueue.NyaQueue.ListTopics:output_type -> nyaqueue.ListTopicsResponse
	13, // 13: nyaqueue.NyaQueue.GetMetrics:output_type -> nyaqueue.MetricsResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_queue_proto_init() }
func file_queue_proto_init() {
	if File_queue_proto != nil {
		return
	}
	file_request_proto_init()
	file_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_proto_goTypes,
		DependencyIndexes: file_queue_proto_depIdxs,
	}.Build()
	File_queue_proto = out.File
	file_queue_proto_goTypes = nil
	file_queue_proto_depIdxs = nil
}
